### ISSUE TITLE
Kebechet getting overwhelmed with requests.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#825]
**Describe the bug**
we have noticed, when there is a surge in the amount of requests coming in from GitHub events,
the kebechect job are getting missed. The reason for this could be multiple as we have lot of interaction point:
1. github webhooks: github might be missing webhook 
2. kafka: user-api sending kafka message for kebechet might be missing
3. consumer: consumer might be skipping over some messages

Incident:
Multiple PRs were opened on the Prescription repo,
at the same time, one of user opened an request for kebechet https://github.com/os-climate/data-platform-demo/issues/12
the event for user was never received by kebechet and missed to serve the user.

Questions to be answered:
from the user side, 
(1) is there a way for us to know when it is happening 
(2) what should we do when it happens?

**Comment by erikerlandson** [comment]
any new developments on resolving this problem?

**Comment by MichaelClifford** [comment]
Any update on this @harshad16 ? we are trying to get kebechet on a couple of the os-climate repo's and it seems like its still not working there. Anything we can do on our end to speed this up?

**Comment by KPostOffice** [comment]
Hey @MichaelClifford this is actually an issue with Kebechet's update manager. It is failing because one of the direct dependencies is not showing up in the Pipfile.lock. If you relock it manually I think it should alleviate your issues. Let me know if there's anything else you need.

For reference:
https://github.com/thoth-station/support/issues/82
This will be fixed by:
https://github.com/thoth-station/kebechet/pull/845

**Comment by KPostOffice** [comment]
> Any update on this @harshad16 ? we are trying to get kebechet on a couple of the os-climate repo's and it seems like its still not working there. Anything we can do on our end to speed this up?

What repositories is it inoperative on? I can run Kebechet locally on a fork in order to make sure that there aren't any other issues.

**Comment by MichaelClifford** [comment]
@KPostOffice Its all the repo's in the OS-Climate org, but you can test it on https://github.com/os-climate/aicoe-osc-demo

Thanks!

**Comment by MichaelClifford** [comment]
> Hey @MichaelClifford this is actually an issue with Kebechet's update manager. It is failing because one of the direct dependencies is not showing up in the Pipfile.lock. If you relock it manually I think it should alleviate your issues. Let me know if there's anything else you need.

For reference:
thoth-station/support#82
This will be fixed by:
#845

@chauhankaranraj can you try this out on the os-climate/aicoe-osc-aicoe repo and see if it gets kebechet working?

**Comment by MichaelClifford** [comment]
cc @Shreyanand

**Comment by MichaelClifford** [comment]
@KPostOffice here is the PR with the newly locked pipfile in our repo. Is this what you meant by your suggestions above? 
https://github.com/os-climate/aicoe-osc-demo/pull/34

**Comment by MichaelClifford** [comment]
What level of access the does Sesheta need as a repo collaborator? Is "Read" sufficient?

**Comment by KPostOffice** [comment]
Hey @MichaelClifford , I think I lost track of what we were actually trying to track with this issue. I think the issue body is still relevant but I have fixed the "package not present in pipfile.lock" issue, so that it no longer must be present in Pipfile.lock. If you've still seen this issue let me know and I'll open a new issue for that.

**Comment by MichaelClifford** [comment]
Thanks @KPostOffice my main concern was getting kebechet to work on the OS-Climate repo's which it is now with [this](https://github.com/thoth-station/thoth-application/pull/2412) PR. But I think otherwise this issue can be closed?

**Comment by KPostOffice** [comment]
I'm going to leave this open because I think tracking requests in vs requests processed for kebechet would be useful. I think the basic way to tell where requests are being lost is by comparing `num_messages_sent`, `num_messages_on_kafka`, and `num_kebechet_run_webhook_workflows`. Ideally all these should be the same.

## TODO:
- [ ] add metric to user-api which tracks messages sent
- [x] metric for num kebechet run webhook messages should already be available through strimzi
- [ ] track num of kebechet run webhook events (is this available through argo somewhere?)
- [ ] create dashboard which plots the three metrics
